- roles/common/tasks/main.yml
- roles/engine-install/tasks/main.yml
I believe that this style is more readable and better for auditing.
It reduces long lines, and make review better.
I would suggest you to adopt this pattern.
> Human readable style of ansible playbook

- roles/ovirt-engine-setup/tasks/main.yml
Adding checks after engine installation for db status, engine service status, engine status after restart, engine healthpage status
> Adding check for ovirt-engine health after installation

- roles/ovirt-common/defaults/main.yml
- roles/ovirt-common/tasks/main.yml
- roles/ovirt-engine-setup/defaults/main.yml
- roles/ovirt-engine-setup/tasks/main.yml
closed selinux package issue
added default values for ovirt_engine_type
needs additional commits
> Basic refactoring for standard installation

- roles/ovirt-common/README.md
- roles/ovirt-common/defaults/main.yml
- roles/ovirt-common/tasks/main.yml
- roles/ovirt-engine-install-packages/README.md
- roles/ovirt-engine-remote-db/README.md
- roles/ovirt-engine-remote-db/defaults/main.yml
- roles/ovirt-engine-remote-db/tasks/main.yml
- roles/ovirt-engine-remote-db/templates/ovirt-engine-db-user-create.sql.j2
- roles/ovirt-engine-remote-db/templates/ovirt-engine-dwh-db-user-create.sql.j2
- roles/ovirt-engine-setup/README.md
- roles/ovirt-engine-setup/defaults/main.yml
- roles/ovirt-engine-setup/tasks/main.yml
- engine & DWH
- user can specify db_name, db_user, db_password..
- setting PostgreSQL: listen_address, port
> Added remote DB support

- python-scripts/generate_hot_tempalte.py
- test-requirements.txt
- tox.ini
Adding also flake8 support for python-scripts to tox
> Heat Orchestration generating script for openstack

- roles/ovirt-collect-logs/README.md
- roles/ovirt-collect-logs/meta/main.yml
- roles/ovirt-collect-logs/tasks/db.yml
- roles/ovirt-collect-logs/tasks/dwh.yml
- roles/ovirt-collect-logs/tasks/engine.yml
- roles/ovirt-collect-logs/tasks/hypervisor.yml
- roles/ovirt-collect-logs/tasks/main.yml
- roles/ovirt-collect-logs/vars/db.yml
- roles/ovirt-collect-logs/vars/dwh.yml
- roles/ovirt-collect-logs/vars/engine.yml
- roles/ovirt-collect-logs/vars/hypervisor.yml
- roles/ovirt-collect-logs/vars/main.yml
> Adding ovirt-engine-collect-logs role

- examples/inventory/provision_hypervisor.inv
- examples/playbooks/provision_hypervisor.yml
Adding an example of provisioning hosts with existing "ovirt-common" role 
#21
> Adding example for provisioning hosts

- roles/ovirt-engine-config/README.md
- roles/ovirt-engine-config/meta/main.yml
- roles/ovirt-engine-config/tasks/main.yml
> Add engine-config role

- roles/ovirt-collect-logs/tasks/main.yml
Add collect of memory usage of processes
> ovirt-collect-logs: collect memory usage

- roles/ovirt-collect-logs/tasks/hypervisor.yml
Add example of collecting logs
related to #60
> Add hosted engine logs ovirt-collect-logs

- roles/ovirt-common/README.md
README in roles/ovirt-common now represents recent changes
> Fix README

- roles/ovirt-collect-logs/tasks/main.yml
- roles/ovirt-collect-logs/vars/main.yml
- roles/ovirt-engine-config/tasks/main.yml
- tox-ansible-lint-test.sh
- tox.ini
Gate job using ansible lint is now checking all
roles instead of playbooks from examples.
Refactor roles to match new requirements.
> Change gate job to check all roles

- roles/ovirt-common/defaults/main.yml
- roles/ovirt-common/tasks/main.yml
define variables as empty strings
fixes: #74
> Resolve deprecated warnings

- roles/ovirt-engine-config/handlers/main.yml
- roles/ovirt-engine-config/tasks/main.yml
New version of ansible-lint added new requirement that are fixed in this patch.
> Add handlers to ovirt-engine-config

- roles/ovirt-collect-logs/tasks/dwh.yml
Add ignore_errors to ovirt-collect-logs/dwh.yml role
> Ignore missing directories on log collecting

- roles/ovirt-common/tasks/main.yml
error is bad string since we try to have error string
free jenkins console
> Minor text change

- roles/ovirt-engine-setup/README.md
- roles/ovirt-engine-setup/defaults/main.yml
- roles/ovirt-engine-setup/templates/answerfile_3.6_basic.txt.j2
- roles/ovirt-engine-setup/templates/answerfile_4.0_basic.txt.j2
> Add option to configure iso domain on engine

- roles/ovirt-engine-setup/templates/answerfile_4.1_upgrade.txt.j2
Added new answer to answer file
Change-Id: Ib4cc897100d79156baee88f750e8cc00a18b2483
> Answerfile: added engineVacuum answer

- roles/ovirt-engine-setup/templates/answerfile_4.1_upgrade.txt.j2
Change-Id: I50b8f57c78aebc4a43df8c28d0d492cf3b92b201
> upgrade answer: add fixDbConfiguration answer

- README.md
- roles/ovirt-guest-agent/README.md
- roles/ovirt-guest-agent/defaults/main.yml
- roles/ovirt-guest-agent/handlers/main.yaml
- roles/ovirt-guest-agent/meta/main.yml
- roles/ovirt-guest-agent/tasks/main.yml
One small comment: I added in the ansible-lint check the -x ANSIBLE0010 because I got this error
> Add role to install ovirt-guest-agent and ensure service is running

- README.md
- examples/inventory/cleanup_engine.inv
- examples/playbooks/cleanup_engine.yml
- roles/ovirt-engine-cleanup/README.md
- roles/ovirt-engine-cleanup/defaults/main.yml
- roles/ovirt-engine-cleanup/templates/answerfile_4.x.txt.j2
- tests/test.yml
- fixed answerfile 4.x
- added link to main readme
- added example to /examples
Fixes #53
> Fixed ovirt-engine-cleanup role

- README.md
- roles/ovirt-guest-agent/README.md
* fixed typo
* added guest host group
* added test section
> README: updated documentation

- roles/ovirt-common/tasks/main.yml
- roles/ovirt-engine-remote-db/tasks/main.yml
- roles/ovirt-engine-setup/tasks/main.yml
Since ansible 2.3 there are new warnings about wrong when statements.
This commit fixes them.
> Fix warnings regarding to when statements

- roles/ovirt-engine-setup/templates/answerfile_4.2_upgrade.txt.j2
Added new answer to upgrade answerfile for 4.2 version.
> Upgrade answerfile: added new option

- README.md
- roles/ovirt-engine-db-dump/README.md
- roles/ovirt-engine-db-dump/defaults/main.yml
- roles/ovirt-engine-db-dump/meta/main.yml
- roles/ovirt-engine-db-dump/tasks/main.yml
ansible role that gets database variables (dabatase name, user, ...) and dump files for engine and DWH
> new role for dumping engine and dwh databases

- roles/ovirt-collect-logs/tasks/main.yml
- tests/engine-deploy.yml
> ovirt-collect-logs: Fix log collection for CentOS 7

- roles/ovirt-collect-logs/tasks/engine.yml
Collect ovirt-provider-ovn.log from engine
> Add provider log to ovirt log collector

- roles/ovirt-common/README.md
- roles/ovirt-engine-remote-db/README.md
- roles/ovirt-engine-remote-db/defaults/main.yml
- roles/ovirt-engine-remote-db/tasks/main.yml
- roles/ovirt-engine-remote-db/templates/ovirt-engine-db-create.sql.j2
- roles/ovirt-engine-remote-db/templates/ovirt-engine-db-user-create.sql.j2
- roles/ovirt-engine-remote-db/templates/ovirt-engine-dwh-db-create.sql.j2
- roles/ovirt-engine-remote-db/templates/ovirt-engine-dwh-db-user-create.sql.j2
- roles/ovirt-engine-remote-db/vars/default.yml
- roles/ovirt-engine-remote-db/vars/postgres95.yml
- roles/ovirt-engine-setup/tasks/main.yml
- tests/db-deploy-master.yml
- tests/db-deploy.yml
- tests/test-3.6.yml
- tests/test-4.0.yml
- tests/test-4.1.yml
- tests/test-master.yml
- tests/test-upgrade-4.0-to-4.1.yml
- tests/test-upgrade-4.1-to-master.yml
service name was changed
its now rh-postgres....
> Postgres new version for master

- roles/ovirt-collect-logs/tasks/db.yml
- roles/ovirt-collect-logs/tasks/dwh.yml
- roles/ovirt-collect-logs/tasks/engine.yml
- roles/ovirt-collect-logs/tasks/hypervisor.yml
- roles/ovirt-collect-logs/tasks/main.yml
- roles/ovirt-engine-backup/tasks/main.yml
- roles/ovirt-engine-config/handlers/main.yml
- roles/ovirt-engine-db-dump/tasks/main.yml
- roles/ovirt-engine-remote-db/tasks/main.yml
- roles/ovirt-engine-remote-dwh/install-postgresql/tasks/main.yml
- roles/ovirt-engine-remote-dwh/tasks/main.yml
- roles/ovirt-engine-rename/tasks/main.yml
- roles/ovirt-guest-agent/tasks/main.yml
- roles/ovirt-iso-uploader-conf/tasks/main.yml
Make the result testing ansible 2.9 compatible 
and remove linter issues [2xx] and [6xx].
> Fix linter
